#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 6

enum {
  sym_name = 1,
  anon_sym_def = 2,
  anon_sym_EQ = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_PLUS = 6,
  anon_sym_DASH = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_if = 10,
  anon_sym_then = 11,
  anon_sym_else = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym__dec = 15,
  sym_val_bind = 16,
  sym__atom = 17,
  sym__exp = 18,
  sym_apply = 19,
  sym_binary = 20,
  sym_neg = 21,
  sym_if = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_apply_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name] = "name",
  [anon_sym_def] = "def",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "symbol",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "symbol",
  [anon_sym_SLASH] = "symbol",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__dec] = "_dec",
  [sym_val_bind] = "val_bind",
  [sym__atom] = "_atom",
  [sym__exp] = "_exp",
  [sym_apply] = "apply",
  [sym_binary] = "binary",
  [sym_neg] = "neg",
  [sym_if] = "if",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_apply_repeat1] = "apply_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name] = sym_name,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_PLUS,
  [anon_sym_SLASH] = anon_sym_PLUS,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__dec] = sym__dec,
  [sym_val_bind] = sym_val_bind,
  [sym__atom] = sym__atom,
  [sym__exp] = sym__exp,
  [sym_apply] = sym_apply,
  [sym_binary] = sym_binary,
  [sym_neg] = sym_neg,
  [sym_if] = sym_if,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_apply_repeat1] = aux_sym_apply_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__dec] = {
    .visible = false,
    .named = true,
  },
  [sym_val_bind] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_neg] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_args = 1,
  field_bindto = 2,
  field_cond = 3,
  field_else = 4,
  field_func = 5,
  field_lhs = 6,
  field_negated = 7,
  field_op = 8,
  field_rhs = 9,
  field_then = 10,
  field_val = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_bindto] = "bindto",
  [field_cond] = "cond",
  [field_else] = "else",
  [field_func] = "func",
  [field_lhs] = "lhs",
  [field_negated] = "negated",
  [field_op] = "op",
  [field_rhs] = "rhs",
  [field_then] = "then",
  [field_val] = "val",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_bindto, 1},
    {field_val, 3},
  [2] =
    {field_negated, 1},
  [3] =
    {field_args, 1},
    {field_func, 0},
  [5] =
    {field_lhs, 0},
    {field_op, 1},
    {field_rhs, 2},
  [8] =
    {field_cond, 1},
    {field_else, 5},
    {field_then, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [4] = {
    [1] = anon_sym_PLUS,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 10,
  [11] = 4,
  [12] = 12,
  [13] = 10,
  [14] = 14,
  [15] = 5,
  [16] = 3,
  [17] = 14,
  [18] = 12,
  [19] = 19,
  [20] = 8,
  [21] = 2,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 27,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 36,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(6);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(40),
    [sym__dec] = STATE(33),
    [sym_val_bind] = STATE(33),
    [aux_sym_source_file_repeat1] = STATE(33),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_def] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(12), 1,
      anon_sym_LPAREN,
    STATE(2), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(17), 3,
      anon_sym_DASH,
      anon_sym_then,
      anon_sym_else,
    ACTIONS(15), 4,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [25] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_name,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(2), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(25), 3,
      anon_sym_DASH,
      anon_sym_then,
      anon_sym_else,
    ACTIONS(23), 4,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [50] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_name,
    STATE(3), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(31), 3,
      anon_sym_DASH,
      anon_sym_then,
      anon_sym_else,
    ACTIONS(29), 4,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [75] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(37), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [101] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(24), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [127] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      anon_sym_if,
    STATE(11), 1,
      sym__atom,
    STATE(31), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [153] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(34), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [179] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      anon_sym_if,
    STATE(11), 1,
      sym__atom,
    STATE(24), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [205] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(32), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [231] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_name,
    ACTIONS(31), 2,
      anon_sym_def,
      anon_sym_DASH,
    STATE(16), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(29), 4,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [255] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(23), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [281] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(38), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [307] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(28), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [333] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(36), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [359] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      sym_name,
    ACTIONS(25), 2,
      anon_sym_def,
      anon_sym_DASH,
    STATE(21), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(23), 4,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [383] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      anon_sym_if,
    STATE(11), 1,
      sym__atom,
    STATE(29), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [409] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      anon_sym_if,
    STATE(11), 1,
      sym__atom,
    STATE(23), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [435] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(45), 1,
      anon_sym_if,
    STATE(11), 1,
      sym__atom,
    STATE(30), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [461] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(35), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [487] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_name,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 2,
      anon_sym_def,
      anon_sym_DASH,
    STATE(21), 2,
      sym__atom,
      aux_sym_apply_repeat1,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [511] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      sym_name,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_if,
    STATE(4), 1,
      sym__atom,
    STATE(27), 5,
      sym__exp,
      sym_apply,
      sym_binary,
      sym_neg,
      sym_if,
  [537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_DASH,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_then,
      anon_sym_else,
  [554] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_DASH,
    ACTIONS(61), 8,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_then,
      anon_sym_else,
  [571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 4,
      anon_sym_DASH,
      anon_sym_then,
      anon_sym_else,
      sym_name,
    ACTIONS(67), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 3,
      anon_sym_def,
      anon_sym_DASH,
      sym_name,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [604] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 3,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [623] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_DASH,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(57), 4,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_then,
      anon_sym_else,
  [640] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_DASH,
    ACTIONS(77), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_def,
      anon_sym_PLUS,
  [656] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      anon_sym_def,
    ACTIONS(77), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [674] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_PLUS,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(77), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_def,
  [692] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(85), 1,
      anon_sym_then,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [709] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_def,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(39), 3,
      sym__dec,
      sym_val_bind,
      aux_sym_source_file_repeat1,
  [724] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [741] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [758] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(93), 1,
      anon_sym_else,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [775] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(95), 1,
      anon_sym_else,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [792] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_PLUS,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(97), 1,
      anon_sym_then,
    ACTIONS(75), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [809] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_def,
    STATE(39), 3,
      sym__dec,
      sym_val_bind,
      aux_sym_source_file_repeat1,
  [824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_EQ,
  [838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 101,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 153,
  [SMALL_STATE(9)] = 179,
  [SMALL_STATE(10)] = 205,
  [SMALL_STATE(11)] = 231,
  [SMALL_STATE(12)] = 255,
  [SMALL_STATE(13)] = 281,
  [SMALL_STATE(14)] = 307,
  [SMALL_STATE(15)] = 333,
  [SMALL_STATE(16)] = 359,
  [SMALL_STATE(17)] = 383,
  [SMALL_STATE(18)] = 409,
  [SMALL_STATE(19)] = 435,
  [SMALL_STATE(20)] = 461,
  [SMALL_STATE(21)] = 487,
  [SMALL_STATE(22)] = 511,
  [SMALL_STATE(23)] = 537,
  [SMALL_STATE(24)] = 554,
  [SMALL_STATE(25)] = 571,
  [SMALL_STATE(26)] = 588,
  [SMALL_STATE(27)] = 604,
  [SMALL_STATE(28)] = 623,
  [SMALL_STATE(29)] = 640,
  [SMALL_STATE(30)] = 656,
  [SMALL_STATE(31)] = 674,
  [SMALL_STATE(32)] = 692,
  [SMALL_STATE(33)] = 709,
  [SMALL_STATE(34)] = 724,
  [SMALL_STATE(35)] = 741,
  [SMALL_STATE(36)] = 758,
  [SMALL_STATE(37)] = 775,
  [SMALL_STATE(38)] = 792,
  [SMALL_STATE(39)] = 809,
  [SMALL_STATE(40)] = 824,
  [SMALL_STATE(41)] = 831,
  [SMALL_STATE(42)] = 838,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2), SHIFT_REPEAT(2),
  [12] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2), SHIFT_REPEAT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 2, .production_id = 3),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_apply, 2, .production_id = 3),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 1),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2), SHIFT_REPEAT(21),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2), SHIFT_REPEAT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, .production_id = 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, .production_id = 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_neg, 2, .production_id = 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_neg, 2, .production_id = 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 6, .production_id = 5),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_val_bind, 4, .production_id = 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [104] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_futhark(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_name,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
